### ISSUE TITLE
Missing 'Classes' folder

### ISSUE THREAD

**Issue by webian** [ku-kom/ku_swiper#1]
Hello,
I cloned the extension and, after clicking "Activate" in TYPO3 BE Extensions module, I get this error because it is missing the "Classes" directory:
`The file "../Classes" does not exist (in: "/typo3conf/ext/ku_swiper/Configuration", "/typo3conf/ext/ku_swiper/Configuration/").`

Manually adding the folder fixes the problem.

**Comment by ku-kom** [comment]
Thank you for reporting this. Gid didn't like my empty Classes folder. Fixed now in v. 1.1.0.
