### ISSUE TITLE
Header fields not visible in BE

### ISSUE THREAD

**Issue by webian** [ku-kom/ku_swiper#2]
Hello,
why is header fields disabled in TCEFORM for ku_swiper and ku_swiper_content?

I understand that often the slider does not need a title, but a title is still useful to name the CE in the BE to be more organized. Without a title, all sliders will display "[No title]" in the BE and it will be difficult for editors to distinguish them.

Why not enable title fields and give editors the ability to set a title as hidden? Or add a title field for the CE that is visible only in the BE like for "shortcut" CE?

If you agree I can work on it and make a PR. :)

**Comment by ku-kom** [comment]
Hi. This extension is very customized and header fields were not needed. However, with this new release I have enabled them. Please feel free to make a solution to give edtors the ability to set a title as hidden. I would be happy to include it.

**Comment by webian** [comment]
Oh well... since in new release header & header_layout fields are no more disabled, the editor can then select 'hidden' as header_layout. We can close this. Thanks!
